const base = require('./jest.config.base');

module.exports = {
  ...base,
  testMatch: ['**/tests/**/*.test.ts'],
  testPathIgnorePatterns: ['\\.integration\\.test\\.ts$'],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/api/generic.ts',
    'src/api/Filter.ts',
    'src/api/Node.ts',
    'src/boot.ts',
    'src/core/cleanup.ts',
    'src/core/cookies.ts',
    'src/core/csrf.ts',
    'src/core/cursor.ts',
    'src/core/database.ts',
    'src/core/migrations.ts',
    'src/core/server-config.ts',
    'src/core/server-request.ts',
    'src/services/FilterService.ts',
    'src/services/IssueService.ts',
    'src/services/PublisherService.ts',
    'src/services/SeriesService.ts',
    'src/services/StoryService.ts',
    'src/services/UserService.ts',
    'src/modules/appearance/Appearance.resolver.ts',
    'src/modules/arc/Arc.resolver.ts',
    'src/modules/cover/Cover.resolver.ts',
    'src/modules/feature/Feature.resolver.ts',
    'src/modules/individual/Individual.resolver.ts',
    'src/modules/issue/Issue.resolver.ts',
    'src/modules/publisher/Publisher.resolver.ts',
    'src/modules/series/Series.resolver.ts',
    'src/modules/story/Story.resolver.ts',
    'src/modules/user/User.resolver.ts',
    'src/types/schemas.ts',
    'src/util/logger.ts',
    'src/util/util.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov', 'json-summary'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
};
