sonar.projectKey=loliman_shortbox-graphql
sonar.organization=loliman
sonar.host.url=https://sonarcloud.io
sonar.newCode.referenceBranch=main
sonar.sources=src
sonar.tests=tests
sonar.cpd.exclusions=src/mock/**,src/crawler/**
sonar.coverage.exclusions=src/mock/**,src/crawler/**,src/api/schema.ts,src/app.ts,src/config/**,src/core/enums/**,src/core/server.ts,src/models/**,src/modules/**/*.model.ts,src/modules/**/*.schema.ts,src/modules/shared/**,src/types/db.ts,src/types/express-session.d.ts,src/types/graphql-sequelize.d.ts,src/types/graphql.ts,src/util/FilterUpdater.ts,src/util/Mapper.ts,src/util/StringUtils.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
