const stories: any[] = [
  {title: 'Journey into Mystery Vol 1 83', state: 'M'},
  {title: 'Tales of Suspense Vol 1 39', state: 'M'},
  {title: 'X-Men: Season One Vol 1 1', state: 'M'},
  {title: 'Hulk Vol 2 23', state: 'M'},
  {title: "Super-Villain Team-Up MODOK's 11 Vol 1 4", state: 'M'},
  {title: 'LEGO Marvel Super Heroes Vol 1 5', state: 'A'},
  {title: 'LEGO Marvel Super Heroes Vol 1 4', state: 'A'},
  {title: 'LEGO Marvel Super Heroes Vol 1 3', state: 'A'},
  {title: 'LEGO Marvel Super Heroes Vol 1 2', state: 'A'},
  {title: 'LEGO Marvel Super Heroes Vol 1 1', state: 'A'},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
  {title: 'Journey into Mystery Vol 1 83', state: ''},
];
